### ISSUE TITLE
The plan of attack

### ISSUE THREAD

**Issue by SimonCropp** [Particular/PlatformInstaller#17]
- [x] [Create a WPF app to act as a Launcher](https://github.com/Particular/PlatformInstaller/issues/22)
- [x] [Define installation and update approach for launcher](https://github.com/Particular/PlatformInstaller/issues/21)
- [x] [Launcher handles installation of Chocolatey](https://github.com/Particular/PlatformInstaller/issues/23)
- [ ] Build and Auto deploy Bootstrap app so we can test it end to end
- [x] Create a Chocolatey account for Particular. put details in lastpass
- [x] Create MSMQ package https://github.com/Particular/PlatformInstaller/issues/15
- [x] Create DTC package https://github.com/Particular/PlatformInstaller/issues/16
- [x] Create Perf Counters package https://github.com/Particular/PlatformInstaller/issues/19
- [x] Create SC Package https://github.com/Particular/ServiceControl/issues/230
- [x] Create SI Package https://github.com/Particular/ServiceInsight/issues/240
- [x] Create SP Package https://github.com/Particular/ServicePulse/issues/97
- [x] Create SM Package https://github.com/Particular/ServiceMatrix/issues/224
- [x] Actions in Bootstrap will trigger the various chocolatey packages
- [x] Add a launch action for RavenDB http://chocolatey.org/packages/RavenDB
- [x] All chocolatey commands run will be shown to the user. This way if they fail the user can better troubleshoot them. Also helps the user learn what is happening on their machine
- [ ] Create doco/FAQ for Chocolatey https://github.com/Particular/PlatformInstaller/issues/14
- [ ] Create doco/FAQ for Launcher https://github.com/Particular/PlatformInstaller/issues/18
- [x] Add a "machine configured" flag. related to https://github.com/Particular/PlatformInstaller/issues/13 and https://github.com/Particular/NServiceBus/issues/1953
- [x] Pop open a webpage showing the users the next steps - https://github.com/Particular/PlatformInstaller/issues/13
- [x] Display the platform EULA

The platform installer **Will Not**
- Install samples
- Install any NServiceBus binaries
